#spring:
#  datasource:
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      initial-size: 0
#      min-idle: 0
#      max-active: 128
#      max-wait: 60000
#      time-between-eviction-runs-millis: 20000
#      min-evictable-idle-time-millis: 300000
#      validation-query: 'SELECT ''x'''
#      test-while-idle: true
#      test-on-borrow: true
#      test-on-return: true
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      filters: 'config,stat'
nacos:
  config:
    endpoint: 'acm.aliyun.com'
    namespace: ''
    access-key: ''
    secret-key: ''