spring:
  application:
    name: demo-consumer
  cloud:
    sentinel:
      eager: true
      enabled: true
      transport:
        dashboard: 127.0.0.1:7070
      filter:
        url-patterns: /**
feign:
  sentinel:
    enabled: true
server:
  port: 8050