spring:
  application:
    name: demo-provider
  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        # nacos 地址
        server-addr: 127.0.0.1:8848
  main:
#    web-application-type: NONE
    web-application-type: none
dubbo:
  scan:
    # dubbo的基准扫描的包
    base-packages: org.dullbird.cloud.dubbo.demo.service
  protocols:
    dubbo:
      # 一开始和下面写重名了，都叫rest，直接报错，@Path错误
      name: dubbo
      # 协议端口，-1 表示自增端口，从 20880 开始
      port: -1
    #rest 协议
    rest:
      name: rest
      port: 9090
      server: netty
  registry:
    # 指定 Dubbo 服务注册中心的地址
    address: spring-cloud://127.0.0.1:8848
  cloud:
    # 订阅服务的关系，''不订阅服务，'*'为订阅所有服务
    subscribed-services: ''