spring:
  application:
    name: demo-provider
  cloud:
    # Nacos 作为注册中心的配置项
    nacos:
      discovery:
        # nacos 地址
        server-addr: 127.0.0.1:8848
dubbo:
  scan:
    # dubbo的基准扫描的包
    base-packages: org.dullbird.cloud.dubbo.demo.service
  protocols:
    dubbo:
      name: dubbo
      # 协议端口，-1 表示自增端口，从 20880 开始
      port: -1
  registry:
    # 指定 Dubbo 服务注册中心的地址
    address: spring-cloud://127.0.0.1:8848
  cloud:
    # 订阅服务的关系，''不订阅服务，'*'为订阅所有服务
    subscribed-services: ''
server:
  port: 18080
